-- 匠人程云数据库员工和权限初始化数据
-- 由 scripts/generate-cloud-seed.mjs 从 portal/auth.js 生成。
-- 执行前请先执行 database/cloud-schema-v1.sql。

begin;

select set_config('app.jrc_initial_password', :'jrc_initial_password', false);

insert into permission_catalog (permission_key, module_key, action_key, display_name, description)
values
  ('ai.access', 'ai', 'access', '课堂反馈AI助手进入', '系统权限'),
  ('paike.access', 'paike', 'access', '排课查看', '系统权限'),
  ('paike.edit', 'paike', 'edit', '排课修改', '系统权限'),
  ('knowledge.access', 'knowledge', 'access', '学管知识库进入', '系统权限'),
  ('knowledge.edit', 'knowledge', 'edit', '学管知识库管理', '系统权限'),
  ('suggestions.access', 'suggestions', 'access', '建议系统进入', '系统权限'),
  ('suggestions.edit', 'suggestions', 'edit', '建议系统管理', '系统权限'),
  ('admissions.access', 'admissions', 'access', '招生进入', '系统权限'),
  ('admissions.edit', 'admissions', 'edit', '招生录入修改', '系统权限'),
  ('admissions.import', 'admissions', 'import', '招生批量导入', '系统权限'),
  ('admissions.export', 'admissions', 'export', '招生数据导出', '系统权限'),
  ('admissions.finance', 'admissions', 'finance', '招生财务归因', '系统权限'),
  ('teachingQuality.access', 'teachingQuality', 'access', '教学质量查看', '系统权限'),
  ('teachingQuality.edit', 'teachingQuality', 'edit', '教学质量管理', '系统权限'),
  ('studentService.access', 'studentService', 'access', '学生服务进入', '系统权限'),
  ('studentService.edit', 'studentService', 'edit', '学生服务管理', '系统权限'),
  ('studentService.create', 'studentService', 'create', '学生服务新增', '系统权限'),
  ('studentService.update', 'studentService', 'update', '学生服务修改', '系统权限'),
  ('studentService.delete', 'studentService', 'delete', '学生服务删除', '系统权限'),
  ('studentService.import', 'studentService', 'import', '学生服务导入', '系统权限'),
  ('studentService.export', 'studentService', 'export', '学生服务导出', '系统权限'),
  ('studentService.reset', 'studentService', 'reset', '学生服务清空', '系统权限'),
  ('curriculum.access', 'curriculum', 'access', '教研课程进入', '系统权限'),
  ('curriculum.edit', 'curriculum', 'edit', '教研课程管理', '系统权限'),
  ('curriculum.create', 'curriculum', 'create', '教研课程新增', '系统权限'),
  ('curriculum.update', 'curriculum', 'update', '教研课程修改', '系统权限'),
  ('curriculum.delete', 'curriculum', 'delete', '教研课程删除', '系统权限'),
  ('curriculum.import', 'curriculum', 'import', '教研课程导入', '系统权限'),
  ('curriculum.export', 'curriculum', 'export', '教研课程导出', '系统权限'),
  ('curriculum.reset', 'curriculum', 'reset', '教研课程清空', '系统权限'),
  ('hr.access', 'hr', 'access', '人事管理进入', '系统权限'),
  ('hr.edit', 'hr', 'edit', '人事管理', '系统权限'),
  ('hr.create', 'hr', 'create', '人事管理新增', '系统权限'),
  ('hr.update', 'hr', 'update', '人事管理修改', '系统权限'),
  ('hr.delete', 'hr', 'delete', '人事管理删除', '系统权限'),
  ('hr.import', 'hr', 'import', '人事管理导入', '系统权限'),
  ('hr.export', 'hr', 'export', '人事管理导出', '系统权限'),
  ('hr.reset', 'hr', 'reset', '人事管理清空', '系统权限'),
  ('campus.access', 'campus', 'access', '校区运营进入', '系统权限'),
  ('campus.edit', 'campus', 'edit', '校区运营管理', '系统权限'),
  ('campus.create', 'campus', 'create', '校区运营新增', '系统权限'),
  ('campus.update', 'campus', 'update', '校区运营修改', '系统权限'),
  ('campus.delete', 'campus', 'delete', '校区运营删除', '系统权限'),
  ('campus.import', 'campus', 'import', '校区运营导入', '系统权限'),
  ('campus.export', 'campus', 'export', '校区运营导出', '系统权限'),
  ('campus.reset', 'campus', 'reset', '校区运营清空', '系统权限'),
  ('videoOps.access', 'videoOps', 'access', '短视频运营进入', '系统权限'),
  ('videoOps.edit', 'videoOps', 'edit', '短视频运营管理', '系统权限'),
  ('finance.access', 'finance', 'access', '财务进入', '系统权限'),
  ('finance.edit', 'finance', 'edit', '财务修改', '系统权限'),
  ('admin.access', 'admin', 'access', '系统管理', '系统权限'),
  ('portal.access', 'portal', 'access', 'portal.access', '系统权限')
on conflict (permission_key) do update set
  module_key = excluded.module_key,
  action_key = excluded.action_key,
  display_name = excluded.display_name,
  description = excluded.description;

delete from role_permission_defaults;

insert into role_permission_defaults (role, permission_key)
values
  ('管理员', 'admin.access'),
  ('管理员', 'ai.access'),
  ('管理员', 'campus.access'),
  ('管理员', 'campus.edit'),
  ('管理员', 'curriculum.access'),
  ('管理员', 'curriculum.edit'),
  ('管理员', 'hr.access'),
  ('管理员', 'hr.edit'),
  ('管理员', 'paike.access'),
  ('管理员', 'portal.access'),
  ('管理员', 'studentService.access'),
  ('管理员', 'studentService.edit'),
  ('管理员', 'suggestions.access'),
  ('管理员', 'teachingQuality.access'),
  ('管理员', 'teachingQuality.edit'),
  ('管理员', 'videoOps.access'),
  ('管理员', 'videoOps.edit'),
  ('学管', 'admissions.access'),
  ('学管', 'admissions.edit'),
  ('学管', 'admissions.export'),
  ('学管', 'admissions.import'),
  ('学管', 'ai.access'),
  ('学管', 'campus.access'),
  ('学管', 'campus.edit'),
  ('学管', 'curriculum.access'),
  ('学管', 'knowledge.access'),
  ('学管', 'paike.access'),
  ('学管', 'portal.access'),
  ('学管', 'studentService.access'),
  ('学管', 'studentService.edit'),
  ('学管', 'suggestions.access'),
  ('学管', 'teachingQuality.access'),
  ('学管', 'teachingQuality.edit'),
  ('学管', 'videoOps.access'),
  ('学管', 'videoOps.edit'),
  ('财务', 'ai.access'),
  ('财务', 'finance.access'),
  ('财务', 'finance.edit'),
  ('财务', 'portal.access'),
  ('财务', 'suggestions.access'),
  ('财务', 'videoOps.access'),
  ('财务', 'videoOps.edit'),
  ('授课老师', 'ai.access'),
  ('授课老师', 'campus.access'),
  ('授课老师', 'curriculum.access'),
  ('授课老师', 'curriculum.create'),
  ('授课老师', 'curriculum.export'),
  ('授课老师', 'curriculum.import'),
  ('授课老师', 'curriculum.update'),
  ('授课老师', 'paike.access'),
  ('授课老师', 'portal.access'),
  ('授课老师', 'studentService.access'),
  ('授课老师', 'suggestions.access'),
  ('授课老师', 'teachingQuality.access'),
  ('试用期老师', 'ai.access'),
  ('试用期老师', 'campus.access'),
  ('试用期老师', 'curriculum.access'),
  ('试用期老师', 'knowledge.access'),
  ('试用期老师', 'paike.access'),
  ('试用期老师', 'portal.access'),
  ('试用期老师', 'studentService.access'),
  ('试用期老师', 'suggestions.access'),
  ('试用期老师', 'teachingQuality.access'),
  ('试用期学管', 'admissions.access'),
  ('试用期学管', 'ai.access'),
  ('试用期学管', 'campus.access'),
  ('试用期学管', 'curriculum.access'),
  ('试用期学管', 'knowledge.access'),
  ('试用期学管', 'paike.access'),
  ('试用期学管', 'portal.access'),
  ('试用期学管', 'studentService.access'),
  ('试用期学管', 'suggestions.access'),
  ('试用期学管', 'teachingQuality.access')
on conflict (role, permission_key) do nothing;

insert into employees (name, username, password_hash, role, phone, wechat, subject, scope, hire_date, regular_date, commission_rate, status, metadata)
values
  ('周珊', 'zhoushan', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '学管', '15212968215', 'Azs-20210113', null, '1-9', '2025-09-01'::date, '2025-10-01'::date, null, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('高芳燕', 'gaofangyan', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '学管', '17879352353', 'jiujiujiujiumii', null, '小课1-9', '2025-09-11'::date, '2025-10-11'::date, null, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('颜雨涵', 'yanyuhan', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '学管', '18892619946', '18892619946', null, '1-4年级', '2023-07-14'::date, '2023-07-14'::date, null, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('徐嘉丽', 'xujiali', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '学管', '18379947202', 'Pluto--Sco-20L', null, '5-6年级', '2026-03-16'::date, '2026-04-16'::date, null, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('程志豪', 'chengzhihao', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '管理员', '15888003051', 'jrc-math', '数学', '1-9年级', '2016-06-20'::date, '2016-07-20'::date, 100, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('陈雨晴', 'chenyuqing', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '财务', '15259085997', 'YQZH5208598', null, '1-9', '2020-10-02'::date, '2020-11-02'::date, null, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('海滢滢', 'haiyingying', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '18758400721', 'cathy125805', '科学', '3-8年级', '2021-03-20'::date, '2021-04-20'::date, 50, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('姚老师', 'yaolaoshi', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', null, null, '数学', '外聘老师', null, null, null, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql', 'settlementRule', '单独按实到人数结算')),
  ('叶源泽', 'yeyuanze', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '13738807822', 'YYZ-May-19', '数学', '初一（七年级）', '2025-05-09'::date, '2025-06-09'::date, 23, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('李舒', 'lishu', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '19155389323', '19155389323', '数学', '一年级、二年级、三年级', '2025-07-05'::date, '2025-08-05'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('刘大君', 'liudajun', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '15639466839', '15639466839', '数学', '初中部教研主任（初一至初三）', '2024-01-20'::date, '2024-01-20'::date, 33.33, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('吴水琴', 'wushuiqin', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '18056627068', 'fmkkii555', '数学', '四年级', '2026-05-16'::date, '2026-06-16'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('朱永乐', 'zhuyongle', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '15205843546', 'L2577593964', '科学', '初一科学（七年级）', '2025-12-12'::date, '2026-06-12'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('郑嘉艺', 'zhengjiayi', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '15968088762', 'Joyee-yiyi', '数学', '初二（八年级）', '2025-12-22'::date, '2026-01-22'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('赵萱', 'zhaoxuan', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '15938462313', 'zx15938462313', '数学', '小学部教研主任（一至六年级）', '2025-09-08'::date, '2025-10-08'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('曹德顺', 'caodeshun', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '18003276656', 'cds030418', '数学', '初二（八年级）', '2026-04-23'::date, '2026-05-23'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('潘云贵', 'panyungui', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '13114114478', 'UNomnipotentyouth', '数学', '五年级', '2026-04-22'::date, '2026-05-22'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql')),
  ('吴建勇', 'wujianyong', crypt(current_setting('app.jrc_initial_password'), gen_salt('bf')), '授课老师', '17816636255', '-Woey1228', '数学', '初一（七年级）', '2026-05-20'::date, '2026-06-20'::date, 20, 'active', jsonb_build_object('needsPasswordChange', true, 'source', 'seed-employees.sql'))
on conflict (username) do update set
  name = excluded.name,
  password_hash = case when employees.password_hash is null then excluded.password_hash else employees.password_hash end,
  role = excluded.role,
  phone = excluded.phone,
  wechat = excluded.wechat,
  subject = excluded.subject,
  scope = excluded.scope,
  hire_date = excluded.hire_date,
  regular_date = excluded.regular_date,
  commission_rate = excluded.commission_rate,
  status = excluded.status,
  metadata = (coalesce(employees.metadata, '{}'::jsonb) - 'initialPasswordPolicy') || case
    when employees.password_hash is null then excluded.metadata
    when coalesce(employees.metadata, '{}'::jsonb) ? 'initialPasswordPolicy' then jsonb_build_object('needsPasswordChange', true)
    else '{}'::jsonb
  end,
  updated_at = now();

delete from employee_permissions;

insert into employee_permissions (employee_id, permission_key, note)
select employees.id, permissions.permission_key, 'initial cloud seed'
from employees
join (values
  ('zhoushan', 'admissions.access'),
  ('zhoushan', 'admissions.edit'),
  ('zhoushan', 'admissions.import'),
  ('zhoushan', 'ai.access'),
  ('zhoushan', 'campus.access'),
  ('zhoushan', 'campus.edit'),
  ('zhoushan', 'curriculum.access'),
  ('zhoushan', 'knowledge.access'),
  ('zhoushan', 'paike.access'),
  ('zhoushan', 'paike.edit'),
  ('zhoushan', 'portal.access'),
  ('zhoushan', 'studentService.access'),
  ('zhoushan', 'studentService.edit'),
  ('zhoushan', 'suggestions.access'),
  ('zhoushan', 'teachingQuality.access'),
  ('zhoushan', 'teachingQuality.edit'),
  ('zhoushan', 'videoOps.access'),
  ('zhoushan', 'videoOps.edit'),
  ('gaofangyan', 'admissions.access'),
  ('gaofangyan', 'admissions.edit'),
  ('gaofangyan', 'admissions.finance'),
  ('gaofangyan', 'admissions.import'),
  ('gaofangyan', 'ai.access'),
  ('gaofangyan', 'campus.access'),
  ('gaofangyan', 'campus.edit'),
  ('gaofangyan', 'curriculum.access'),
  ('gaofangyan', 'knowledge.access'),
  ('gaofangyan', 'knowledge.edit'),
  ('gaofangyan', 'paike.access'),
  ('gaofangyan', 'portal.access'),
  ('gaofangyan', 'studentService.access'),
  ('gaofangyan', 'studentService.edit'),
  ('gaofangyan', 'suggestions.access'),
  ('gaofangyan', 'teachingQuality.access'),
  ('gaofangyan', 'teachingQuality.edit'),
  ('gaofangyan', 'videoOps.access'),
  ('gaofangyan', 'videoOps.edit'),
  ('yanyuhan', 'admissions.access'),
  ('yanyuhan', 'admissions.edit'),
  ('yanyuhan', 'admissions.finance'),
  ('yanyuhan', 'admissions.import'),
  ('yanyuhan', 'ai.access'),
  ('yanyuhan', 'campus.access'),
  ('yanyuhan', 'campus.edit'),
  ('yanyuhan', 'curriculum.access'),
  ('yanyuhan', 'knowledge.access'),
  ('yanyuhan', 'knowledge.edit'),
  ('yanyuhan', 'paike.access'),
  ('yanyuhan', 'portal.access'),
  ('yanyuhan', 'studentService.access'),
  ('yanyuhan', 'studentService.edit'),
  ('yanyuhan', 'suggestions.access'),
  ('yanyuhan', 'teachingQuality.access'),
  ('yanyuhan', 'teachingQuality.edit'),
  ('yanyuhan', 'videoOps.access'),
  ('yanyuhan', 'videoOps.edit'),
  ('xujiali', 'admissions.access'),
  ('xujiali', 'admissions.edit'),
  ('xujiali', 'admissions.import'),
  ('xujiali', 'ai.access'),
  ('xujiali', 'campus.access'),
  ('xujiali', 'campus.edit'),
  ('xujiali', 'curriculum.access'),
  ('xujiali', 'knowledge.access'),
  ('xujiali', 'paike.access'),
  ('xujiali', 'portal.access'),
  ('xujiali', 'studentService.access'),
  ('xujiali', 'studentService.edit'),
  ('xujiali', 'suggestions.access'),
  ('xujiali', 'teachingQuality.access'),
  ('xujiali', 'teachingQuality.edit'),
  ('xujiali', 'videoOps.access'),
  ('xujiali', 'videoOps.edit'),
  ('chengzhihao', 'admin.access'),
  ('chengzhihao', 'admissions.access'),
  ('chengzhihao', 'admissions.edit'),
  ('chengzhihao', 'admissions.export'),
  ('chengzhihao', 'admissions.finance'),
  ('chengzhihao', 'admissions.import'),
  ('chengzhihao', 'ai.access'),
  ('chengzhihao', 'campus.access'),
  ('chengzhihao', 'campus.create'),
  ('chengzhihao', 'campus.delete'),
  ('chengzhihao', 'campus.edit'),
  ('chengzhihao', 'campus.export'),
  ('chengzhihao', 'campus.import'),
  ('chengzhihao', 'campus.reset'),
  ('chengzhihao', 'campus.update'),
  ('chengzhihao', 'curriculum.access'),
  ('chengzhihao', 'curriculum.create'),
  ('chengzhihao', 'curriculum.delete'),
  ('chengzhihao', 'curriculum.edit'),
  ('chengzhihao', 'curriculum.export'),
  ('chengzhihao', 'curriculum.import'),
  ('chengzhihao', 'curriculum.reset'),
  ('chengzhihao', 'curriculum.update'),
  ('chengzhihao', 'finance.access'),
  ('chengzhihao', 'finance.edit'),
  ('chengzhihao', 'hr.access'),
  ('chengzhihao', 'hr.create'),
  ('chengzhihao', 'hr.delete'),
  ('chengzhihao', 'hr.edit'),
  ('chengzhihao', 'hr.export'),
  ('chengzhihao', 'hr.import'),
  ('chengzhihao', 'hr.reset'),
  ('chengzhihao', 'hr.update'),
  ('chengzhihao', 'knowledge.access'),
  ('chengzhihao', 'knowledge.edit'),
  ('chengzhihao', 'paike.access'),
  ('chengzhihao', 'paike.edit'),
  ('chengzhihao', 'portal.access'),
  ('chengzhihao', 'studentService.access'),
  ('chengzhihao', 'studentService.create'),
  ('chengzhihao', 'studentService.delete'),
  ('chengzhihao', 'studentService.edit'),
  ('chengzhihao', 'studentService.export'),
  ('chengzhihao', 'studentService.import'),
  ('chengzhihao', 'studentService.reset'),
  ('chengzhihao', 'studentService.update'),
  ('chengzhihao', 'suggestions.access'),
  ('chengzhihao', 'suggestions.edit'),
  ('chengzhihao', 'teachingQuality.access'),
  ('chengzhihao', 'teachingQuality.edit'),
  ('chengzhihao', 'videoOps.access'),
  ('chengzhihao', 'videoOps.edit'),
  ('chenyuqing', 'admin.access'),
  ('chenyuqing', 'admissions.access'),
  ('chenyuqing', 'admissions.edit'),
  ('chenyuqing', 'admissions.export'),
  ('chenyuqing', 'admissions.finance'),
  ('chenyuqing', 'admissions.import'),
  ('chenyuqing', 'ai.access'),
  ('chenyuqing', 'campus.access'),
  ('chenyuqing', 'campus.create'),
  ('chenyuqing', 'campus.delete'),
  ('chenyuqing', 'campus.edit'),
  ('chenyuqing', 'campus.export'),
  ('chenyuqing', 'campus.import'),
  ('chenyuqing', 'campus.reset'),
  ('chenyuqing', 'campus.update'),
  ('chenyuqing', 'curriculum.access'),
  ('chenyuqing', 'curriculum.create'),
  ('chenyuqing', 'curriculum.delete'),
  ('chenyuqing', 'curriculum.edit'),
  ('chenyuqing', 'curriculum.export'),
  ('chenyuqing', 'curriculum.import'),
  ('chenyuqing', 'curriculum.reset'),
  ('chenyuqing', 'curriculum.update'),
  ('chenyuqing', 'finance.access'),
  ('chenyuqing', 'finance.edit'),
  ('chenyuqing', 'hr.access'),
  ('chenyuqing', 'hr.create'),
  ('chenyuqing', 'hr.delete'),
  ('chenyuqing', 'hr.edit'),
  ('chenyuqing', 'hr.export'),
  ('chenyuqing', 'hr.import'),
  ('chenyuqing', 'hr.reset'),
  ('chenyuqing', 'hr.update'),
  ('chenyuqing', 'knowledge.access'),
  ('chenyuqing', 'knowledge.edit'),
  ('chenyuqing', 'paike.access'),
  ('chenyuqing', 'paike.edit'),
  ('chenyuqing', 'portal.access'),
  ('chenyuqing', 'studentService.access'),
  ('chenyuqing', 'studentService.create'),
  ('chenyuqing', 'studentService.delete'),
  ('chenyuqing', 'studentService.edit'),
  ('chenyuqing', 'studentService.export'),
  ('chenyuqing', 'studentService.import'),
  ('chenyuqing', 'studentService.reset'),
  ('chenyuqing', 'studentService.update'),
  ('chenyuqing', 'suggestions.access'),
  ('chenyuqing', 'suggestions.edit'),
  ('chenyuqing', 'teachingQuality.access'),
  ('chenyuqing', 'teachingQuality.edit'),
  ('chenyuqing', 'videoOps.access'),
  ('chenyuqing', 'videoOps.edit'),
  ('haiyingying', 'admin.access'),
  ('haiyingying', 'admissions.access'),
  ('haiyingying', 'admissions.edit'),
  ('haiyingying', 'admissions.export'),
  ('haiyingying', 'admissions.finance'),
  ('haiyingying', 'admissions.import'),
  ('haiyingying', 'ai.access'),
  ('haiyingying', 'campus.access'),
  ('haiyingying', 'campus.create'),
  ('haiyingying', 'campus.delete'),
  ('haiyingying', 'campus.edit'),
  ('haiyingying', 'campus.export'),
  ('haiyingying', 'campus.import'),
  ('haiyingying', 'campus.reset'),
  ('haiyingying', 'campus.update'),
  ('haiyingying', 'curriculum.access'),
  ('haiyingying', 'curriculum.create'),
  ('haiyingying', 'curriculum.delete'),
  ('haiyingying', 'curriculum.edit'),
  ('haiyingying', 'curriculum.export'),
  ('haiyingying', 'curriculum.import'),
  ('haiyingying', 'curriculum.reset'),
  ('haiyingying', 'curriculum.update'),
  ('haiyingying', 'finance.access'),
  ('haiyingying', 'finance.edit'),
  ('haiyingying', 'hr.access'),
  ('haiyingying', 'hr.create'),
  ('haiyingying', 'hr.delete'),
  ('haiyingying', 'hr.edit'),
  ('haiyingying', 'hr.export'),
  ('haiyingying', 'hr.import'),
  ('haiyingying', 'hr.reset'),
  ('haiyingying', 'hr.update'),
  ('haiyingying', 'knowledge.access'),
  ('haiyingying', 'knowledge.edit'),
  ('haiyingying', 'paike.access'),
  ('haiyingying', 'paike.edit'),
  ('haiyingying', 'portal.access'),
  ('haiyingying', 'studentService.access'),
  ('haiyingying', 'studentService.create'),
  ('haiyingying', 'studentService.delete'),
  ('haiyingying', 'studentService.edit'),
  ('haiyingying', 'studentService.export'),
  ('haiyingying', 'studentService.import'),
  ('haiyingying', 'studentService.reset'),
  ('haiyingying', 'studentService.update'),
  ('haiyingying', 'suggestions.access'),
  ('haiyingying', 'suggestions.edit'),
  ('haiyingying', 'teachingQuality.access'),
  ('haiyingying', 'teachingQuality.edit'),
  ('haiyingying', 'videoOps.access'),
  ('haiyingying', 'videoOps.edit'),
  ('yaolaoshi', 'ai.access'),
  ('yaolaoshi', 'campus.access'),
  ('yaolaoshi', 'curriculum.access'),
  ('yaolaoshi', 'curriculum.create'),
  ('yaolaoshi', 'curriculum.export'),
  ('yaolaoshi', 'curriculum.import'),
  ('yaolaoshi', 'curriculum.update'),
  ('yaolaoshi', 'paike.access'),
  ('yaolaoshi', 'portal.access'),
  ('yaolaoshi', 'studentService.access'),
  ('yaolaoshi', 'suggestions.access'),
  ('yaolaoshi', 'teachingQuality.access'),
  ('yeyuanze', 'ai.access'),
  ('yeyuanze', 'campus.access'),
  ('yeyuanze', 'curriculum.access'),
  ('yeyuanze', 'curriculum.create'),
  ('yeyuanze', 'curriculum.export'),
  ('yeyuanze', 'curriculum.import'),
  ('yeyuanze', 'curriculum.update'),
  ('yeyuanze', 'paike.access'),
  ('yeyuanze', 'portal.access'),
  ('yeyuanze', 'studentService.access'),
  ('yeyuanze', 'suggestions.access'),
  ('yeyuanze', 'suggestions.edit'),
  ('yeyuanze', 'teachingQuality.access'),
  ('lishu', 'ai.access'),
  ('lishu', 'campus.access'),
  ('lishu', 'curriculum.access'),
  ('lishu', 'curriculum.create'),
  ('lishu', 'curriculum.export'),
  ('lishu', 'curriculum.import'),
  ('lishu', 'curriculum.update'),
  ('lishu', 'paike.access'),
  ('lishu', 'portal.access'),
  ('lishu', 'studentService.access'),
  ('lishu', 'suggestions.access'),
  ('lishu', 'teachingQuality.access'),
  ('liudajun', 'ai.access'),
  ('liudajun', 'campus.access'),
  ('liudajun', 'curriculum.access'),
  ('liudajun', 'curriculum.create'),
  ('liudajun', 'curriculum.export'),
  ('liudajun', 'curriculum.import'),
  ('liudajun', 'curriculum.update'),
  ('liudajun', 'finance.access'),
  ('liudajun', 'finance.edit'),
  ('liudajun', 'paike.access'),
  ('liudajun', 'portal.access'),
  ('liudajun', 'studentService.access'),
  ('liudajun', 'suggestions.access'),
  ('liudajun', 'teachingQuality.access'),
  ('wushuiqin', 'ai.access'),
  ('wushuiqin', 'campus.access'),
  ('wushuiqin', 'curriculum.access'),
  ('wushuiqin', 'curriculum.create'),
  ('wushuiqin', 'curriculum.export'),
  ('wushuiqin', 'curriculum.import'),
  ('wushuiqin', 'curriculum.update'),
  ('wushuiqin', 'paike.access'),
  ('wushuiqin', 'portal.access'),
  ('wushuiqin', 'studentService.access'),
  ('wushuiqin', 'suggestions.access'),
  ('wushuiqin', 'teachingQuality.access'),
  ('zhuyongle', 'ai.access'),
  ('zhuyongle', 'campus.access'),
  ('zhuyongle', 'curriculum.access'),
  ('zhuyongle', 'curriculum.create'),
  ('zhuyongle', 'curriculum.export'),
  ('zhuyongle', 'curriculum.import'),
  ('zhuyongle', 'curriculum.update'),
  ('zhuyongle', 'paike.access'),
  ('zhuyongle', 'portal.access'),
  ('zhuyongle', 'studentService.access'),
  ('zhuyongle', 'suggestions.access'),
  ('zhuyongle', 'teachingQuality.access'),
  ('zhengjiayi', 'ai.access'),
  ('zhengjiayi', 'campus.access'),
  ('zhengjiayi', 'curriculum.access'),
  ('zhengjiayi', 'curriculum.create'),
  ('zhengjiayi', 'curriculum.export'),
  ('zhengjiayi', 'curriculum.import'),
  ('zhengjiayi', 'curriculum.update'),
  ('zhengjiayi', 'paike.access'),
  ('zhengjiayi', 'portal.access'),
  ('zhengjiayi', 'studentService.access'),
  ('zhengjiayi', 'suggestions.access'),
  ('zhengjiayi', 'teachingQuality.access'),
  ('zhengjiayi', 'teachingQuality.edit'),
  ('zhaoxuan', 'ai.access'),
  ('zhaoxuan', 'campus.access'),
  ('zhaoxuan', 'curriculum.access'),
  ('zhaoxuan', 'curriculum.create'),
  ('zhaoxuan', 'curriculum.export'),
  ('zhaoxuan', 'curriculum.import'),
  ('zhaoxuan', 'curriculum.update'),
  ('zhaoxuan', 'paike.access'),
  ('zhaoxuan', 'portal.access'),
  ('zhaoxuan', 'studentService.access'),
  ('zhaoxuan', 'suggestions.access'),
  ('zhaoxuan', 'suggestions.edit'),
  ('zhaoxuan', 'teachingQuality.access'),
  ('caodeshun', 'ai.access'),
  ('caodeshun', 'campus.access'),
  ('caodeshun', 'curriculum.access'),
  ('caodeshun', 'curriculum.create'),
  ('caodeshun', 'curriculum.export'),
  ('caodeshun', 'curriculum.import'),
  ('caodeshun', 'curriculum.update'),
  ('caodeshun', 'paike.access'),
  ('caodeshun', 'portal.access'),
  ('caodeshun', 'studentService.access'),
  ('caodeshun', 'suggestions.access'),
  ('caodeshun', 'teachingQuality.access'),
  ('panyungui', 'ai.access'),
  ('panyungui', 'campus.access'),
  ('panyungui', 'curriculum.access'),
  ('panyungui', 'curriculum.create'),
  ('panyungui', 'curriculum.export'),
  ('panyungui', 'curriculum.import'),
  ('panyungui', 'curriculum.update'),
  ('panyungui', 'paike.access'),
  ('panyungui', 'portal.access'),
  ('panyungui', 'studentService.access'),
  ('panyungui', 'suggestions.access'),
  ('panyungui', 'teachingQuality.access'),
  ('wujianyong', 'ai.access'),
  ('wujianyong', 'campus.access'),
  ('wujianyong', 'curriculum.access'),
  ('wujianyong', 'curriculum.create'),
  ('wujianyong', 'curriculum.export'),
  ('wujianyong', 'curriculum.import'),
  ('wujianyong', 'curriculum.update'),
  ('wujianyong', 'paike.access'),
  ('wujianyong', 'portal.access'),
  ('wujianyong', 'studentService.access'),
  ('wujianyong', 'suggestions.access'),
  ('wujianyong', 'teachingQuality.access')
) as permissions(username, permission_key) on permissions.username = employees.username
on conflict (employee_id, permission_key) do nothing;

insert into cloud_migration_runs (migration_key, phase, status, started_at, finished_at, summary)
values ('seed-employees-v1', 'phase-1-foundation', 'finished', now(), now(), 'Seeded employees and permissions from portal/auth.js')
on conflict (migration_key) do update set
  status = excluded.status,
  finished_at = now(),
  summary = excluded.summary;

commit;
